### ISSUE TITLE
how to generate the default value of an attribute to the python class

### ISSUE THREAD

**Issue by wulidaoxue** [pyecore/pyecoregen#25]
the default value of an attribute in ecore file is not generated to the python class. I can't find it in the document. 
any way to do it?
thank you very much

**Comment by aranega** [comment]
Hi @wulidaoxue 

I'm really sorry for the late late answer, this issue totally passed under my radar... The problem you experienced with `defaultLiteralValue` (if you used that in your metamodel) had been fixed in PyEcore with [this commit](https://github.com/pyecore/pyecore/commit/204089bb9f9ef746fdf0ec3e22f4632a897d2ff5). By side effect, it fixed your issue (I just test it). Again, I'm sorry about the really late answer...
